# Generated by Django 3.0 on 2020-01-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='newss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=500)),
                ('desc', models.TextField(max_length=500)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
